server:
  port: 10003

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: localhost:${spring.application.instance_id:${server.port}}
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: 10003

management:
  endpoints:
    web:
      exposure:
        include: health,info
