version: '3.8'
name: sodam
services:
  db:
    image: mariadb:11.7.2
    container_name: maria-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s1o2d3a4m5
      MYSQL_DATABASE: sodam
      MYSQL_USER: sodam
      MYSQL_PASSWORD: 1s2o3d4a5m
    volumes:
      - maria-db:/var/lib/mysql
    networks:
      - spring-network

  eureka-server:
    build:
      context: ../eureka-server/
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  transaction-service:
    build:
      context: ../transaction-service/
      dockerfile: Dockerfile
    container_name: transaction-service
    depends_on:
      - eureka-server
    ports:
      - "10001:10001"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  user-service:
    build:
      context: ../user-service/
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - eureka-server
    ports:
      - "10002:10002"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  gateway-service:
    build:
      context: ../gateway-service/
      dockerfile: Dockerfile
    container_name: gateway-service
    depends_on:
      - eureka-server
    ports:
      - "10003:10003"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  category-service:
    build:
      context: ../category-service/
      dockerfile: Dockerfile
    container_name: category-service
    depends_on:
      - eureka-server
    ports:
      - "10004:10004"
    networks:
      - spring-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  maria-db: 

networks:
  spring-network:
    driver: bridge
