server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId}, spanId=%X{spanId}]"

management:
  tracing:
    sampling:
      probability: 1.0
