server:
  port: 10004 # 서버 실행 포트

spring:
  jmx:
    enabled: false
  application:
    name: accountBook-service # 애플리케이션 이름

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:10002/} # Config 서버 import (환경변수 사용 가능, optional)
